// Type declarations for the external-api service
// (Ordinarily generated by openapi-typescript; do not commit hand edits without review.)

declare module 'external-api' {
  export interface ApiUser {
    id: string;
    email: string;
    displayName: string;
    createdAt: string;
  }

  export interface ApiOrder {
    id: number;
    userId: number;
    amount: number;
    currency: string;
    status: 'pending' | 'paid' | 'shipped';
  }

  export interface ApiSession {
    token: string;
    expiresAt: number;
    userId: number;
  }

  export function fetchUser(id: number): Promise<ApiUser | null>;
  export function fetchOrdersByUser(userId: number): Promise<ApiOrder[]>;
  export function createSession(userId: number, token: string): Promise<ApiSession>;
}
