"""Command-line entry point for the myapp record processor.

The console script generated by pip install (per project.scripts in
pyproject.toml) is `myapp = myapp.cli:main`. Loading this module
therefore fires every top-level import in this file and in every module
this file imports transitively, before argparse has a chance to run.
"""

import argparse
import json
import sys
from pathlib import Path

from myapp import helpers


def _load_records(input_path):
    with open(input_path, "rb") as f:
        payload = json.loads(f.read().decode("utf-8"))
    if not isinstance(payload, list):
        raise ValueError(
            f"input at {input_path} must be a JSON list of record objects, got {type(payload).__name__}"
        )
    for i, r in enumerate(payload):
        if not isinstance(r, dict) or "id" not in r or "value" not in r:
            raise ValueError(
                f"record at index {i} must be an object with 'id' and 'value' keys, got {r!r}"
            )
    return payload


def _build_parser():
    parser = argparse.ArgumentParser(
        prog="myapp",
        description="Process a JSON list of records and write the normalized result.",
    )
    sub = parser.add_subparsers(dest="cmd", required=True)

    proc = sub.add_parser("process", help="Read records from an input file and write processed output.")
    proc.add_argument("input", type=Path, help="Path to a JSON file holding a list of records.")
    proc.add_argument(
        "--output",
        type=Path,
        default=Path("/workspace/output.txt"),
        help="Path to write the processed output to (default: /workspace/output.txt).",
    )
    return parser


def main(argv=None):
    parser = _build_parser()
    args = parser.parse_args(argv)
    if args.cmd == "process":
        records = _load_records(args.input)
        payload_bytes = helpers.process_records(records)
        args.output.write_bytes(payload_bytes)
        return 0
    parser.error(f"unknown subcommand {args.cmd!r}")
    return 2


if __name__ == "__main__":
    sys.exit(main())
